    WITH cols AS (
        SELECT column_name
        FROM intercom.information_schema.columns
        WHERE table_schema = 'STG'
          AND table_name   = 'STG_CONVERSATION_PARTS'
        ORDER BY ordinal_position
    )
    SELECT LISTAGG(
             'SELECT '''||column_name||''' AS column_name, '||
             'COUNT(DISTINCT "'||column_name||'") AS distinct_cnt '||
             'FROM "INTERCOM"."STG"."STG_CONVERSATION_PARTS"',
             ' UNION ALL '
           )
    FROM cols;

--The results of the previous query helps us create the following query.
--The goal of the following query is to gather the columns that have 1 or less category values.
--As they add no information, these columns will not be added to the dim_conversations view.


SELECT * FROM (
SELECT 'ASSIGNED_TO' AS column_name, COUNT(DISTINCT "ASSIGNED_TO") AS distinct_cnt FROM "INTERCOM"."STG"."STG_CONVERSATION_PARTS" UNION ALL SELECT 'ATTACHMENTS' AS column_name, COUNT(DISTINCT "ATTACHMENTS") AS distinct_cnt FROM "INTERCOM"."STG"."STG_CONVERSATION_PARTS" UNION ALL SELECT 'AUTHOR' AS column_name, COUNT(DISTINCT "AUTHOR") AS distinct_cnt FROM "INTERCOM"."STG"."STG_CONVERSATION_PARTS" UNION ALL SELECT 'TYPE' AS column_name, COUNT(DISTINCT "TYPE") AS distinct_cnt FROM "INTERCOM"."STG"."STG_CONVERSATION_PARTS" UNION ALL SELECT 'UPDATED_AT' AS column_name, COUNT(DISTINCT "UPDATED_AT") AS distinct_cnt FROM "INTERCOM"."STG"."STG_CONVERSATION_PARTS" UNION ALL SELECT '_SDC_SEQUENCE' AS column_name, COUNT(DISTINCT "_SDC_SEQUENCE") AS distinct_cnt FROM "INTERCOM"."STG"."STG_CONVERSATION_PARTS" UNION ALL SELECT '_SDC_TABLE_VERSION' AS column_name, COUNT(DISTINCT "_SDC_TABLE_VERSION") AS distinct_cnt FROM "INTERCOM"."STG"."STG_CONVERSATION_PARTS" UNION ALL SELECT 'CONVERSATION_ID' AS column_name, COUNT(DISTINCT "CONVERSATION_ID") AS distinct_cnt FROM "INTERCOM"."STG"."STG_CONVERSATION_PARTS" UNION ALL SELECT 'CONVERSATION_UPDATED_AT' AS column_name, COUNT(DISTINCT "CONVERSATION_UPDATED_AT") AS distinct_cnt FROM "INTERCOM"."STG"."STG_CONVERSATION_PARTS" UNION ALL SELECT 'CREATED_AT' AS column_name, COUNT(DISTINCT "CREATED_AT") AS distinct_cnt FROM "INTERCOM"."STG"."STG_CONVERSATION_PARTS" UNION ALL SELECT 'CONVERSATION_CREATED_AT' AS column_name, COUNT(DISTINCT "CONVERSATION_CREATED_AT") AS distinct_cnt FROM "INTERCOM"."STG"."STG_CONVERSATION_PARTS" UNION ALL SELECT '_SDC_BATCHED_AT' AS column_name, COUNT(DISTINCT "_SDC_BATCHED_AT") AS distinct_cnt FROM "INTERCOM"."STG"."STG_CONVERSATION_PARTS" UNION ALL SELECT '_SDC_EXTRACTED_AT' AS column_name, COUNT(DISTINCT "_SDC_EXTRACTED_AT") AS distinct_cnt FROM "INTERCOM"."STG"."STG_CONVERSATION_PARTS" UNION ALL SELECT '_SDC_RECEIVED_AT' AS column_name, COUNT(DISTINCT "_SDC_RECEIVED_AT") AS distinct_cnt FROM "INTERCOM"."STG"."STG_CONVERSATION_PARTS" UNION ALL SELECT 'ID' AS column_name, COUNT(DISTINCT "ID") AS distinct_cnt FROM "INTERCOM"."STG"."STG_CONVERSATION_PARTS" UNION ALL SELECT 'NOTIFIED_AT' AS column_name, COUNT(DISTINCT "NOTIFIED_AT") AS distinct_cnt FROM "INTERCOM"."STG"."STG_CONVERSATION_PARTS" UNION ALL SELECT 'PART_GROUP' AS column_name, COUNT(DISTINCT "PART_GROUP") AS distinct_cnt FROM "INTERCOM"."STG"."STG_CONVERSATION_PARTS"
)
order by 2